export const Works = [
  {
    id: 1,
    image: "/skills/javascript.png",
    title: "Fullstack Developer",
    company: "Javascript.info",
    period: "Oct 2022 - Mar 2023",
    status: true,
    description: [
      "Develop and maintain JavaScript code",
      "Collaborate with frontend and backend teams",
      "Implement responsive designs using Tailwind CSS",
      "Optimize application performance",
    ],
    technologies: ["Reactjs", "Nodejs", "Expressjs", "Postgresql", "Tailwind"],
  },
  {
    id: 2,
    image: "/skills/typescript.png",
    title: "Frontend Developer",
    company: "React Academy",
    period: "Jan 2023 - Jun 2023",
    status: true,
    description: [
      "Build dynamic UI components with React",
      "Handle API integration using Axios",
      "Manage global state using Redux Toolkit",
      "Ensure mobile responsiveness",
    ],
    technologies: ["Reactjs", "Redux", "Tailwind", "Vite", "Typescript"],
  },
  {
    id: 3,
    image: "/skills/golang.png",
    title: "Backend Developer",
    company: "Node Masters",
    period: "Jul 2023 - Dec 2023",
    status: true,
    description: [
      "Design RESTful APIs with Express",
      "Integrate PostgreSQL database",
      "Implement authentication and authorization",
      "Deploy services to cloud platforms",
    ],
    technologies: ["Nodejs", "Expressjs", "Postgresql", "Docker", "AWS"],
  },
  {
    id: 4,
    image: "/skills/python.png",
    title: "Fullstack Engineer",
    company: "Tech Solutions",
    period: "Jan 2024 - Present",
    status: true,
    description: [
      "Lead fullstack development projects",
      "Architect scalable backend systems",
      "Develop reusable UI components",
      "Mentor junior developers",
    ],
    technologies: ["Next.js", "NestJS", "Prisma", "Postgresql", "Tailwind"],
  },
  {
    id: 5,
    image: "/skills/typescript.png",
    title: "Software Engineer",
    company: "TypeScript Hub",
    period: "May 2023 - Present",
    status: true,
    description: [
      "Develop and maintain TypeScript projects",
      "Refactor legacy JavaScript codebases",
      "Implement advanced TypeScript features",
      "Collaborate in agile development teams",
    ],
    technologies: ["Typescript", "Reactjs", "Nodejs", "GraphQL", "Tailwind"],
  },
];
